insert into parking_spot values(next value FOR spot_id_seq,'p1-01','small regular spot','regular','small','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-02','small regular spot','regular','small','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-03','small handicapped spot','handicapped','small','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-04','small compact spot','compact','small','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-05','small compact spot','compact','small','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-06','small regular spot','regular','small','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-07','medium regular spot','regular','medium','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-08','medium regular spot','regular','medium','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-09','medium handicapped spot','handicapped','medium','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-10','medium compact spot','compact','medium','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-11','medium compact spot','compact','medium','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-12','medium regular spot','regular','medium','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-13','large regular spot','regular','large','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-14','large regular spot','regular','large','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-15','large handicapped spot','handicapped','large','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-16','large compact spot','compact','large','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-17','large compact spot','compact','large','N');
insert into parking_spot values(next value FOR spot_id_seq,'p1-18','large regular spot','regular','large','N');
insert into parking_spcification values(1,'small','two_wheeler');
insert into parking_spcification values(2,'medium','two_wheeler');
insert into parking_spcification values(3,'large','two_wheeler');
insert into parking_spcification values(4,'medium','car');
insert into parking_spcification values(5,'large','car');
insert into parking_spcification values(6,'large','bus');